#A sample Gemfile
source "https://rubygems.org"

gem "rails"
gem 'sinatra'
gem 'sqlite3'
gem 'activerecord', :require => 'active_record'
gem 'rake'
gem 'pry'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'require_all'
gem 'shotgun'
gem 'bcrypt'
gem 'rack-flash3'